### ISSUE TITLE
Port Temporal_WIENER.m

### ISSUE THREAD

**Issue by kjurek** [kjurek/pyTotalActivation#7]
- [ ] Port only implementation from Temporal_WIENER.m file and assume that dependencies from other files are already implemented
- [ ] Create comparison tests with matlab implementation.

**Comment by mfalkiewicz** [comment]
Turns out there are two Wiener implementations, with only one being actually evoked in the MATLAB code. Pending further investigation.

**Comment by mfalkiewicz** [comment]
After consulting with the author of the original code, Temporal_WIENER can be ditched - the winner method from _temporal method is sufficient.
